platform :ios, '13.0'
  use_frameworks!
  inhibit_all_warnings!

def commmon
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'SwiftLint'
end

target 'BetterRefriger' do
  commmon
end


target 'BetterRefrigerTests' do
  commmon
end
