target 'BetterRefriger' do
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'XLPagerTabStrip'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'Then'
  pod 'SwiftLint'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['RxCocoa','RxSwift','SnapKit','Then','XLPagerTabStrip'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
      else
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end  end
end

target 'BetterRefrigerTests' do
  inherit! :search_paths
  pod 'Firebase'
end

end
